version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "18:30"
          timezone: "America/Los_Angeles"
      ignore:
          # Temporarily ignore react and react-dom major updates due to issue with React v18
          - dependency-name: "react"
            update-types: ["version-update:semver-major"]
          - dependency-name: "react-dom"
            update-types: ["version-update:semver-major"]
