version: 2
updates:
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "daily"
            time: "18:30"
            timezone: "America/Los_Angeles"
        ignore:
            -   dependency-name: "sass"
