name: Dependabot Auto Merge

on:
    pull_request:
        branches: [ master ]

jobs:
    auto-merge:
        runs-on: ubuntu-latest
        steps:
        - uses: ahmadnassri/action-dependabot-auto-merge@v2
          with:
              github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
              target: minor
