name: Deploy

on:
    push:
        branches: [ master ]
        paths-ignore:
            - '.github/**'
            - 'README.md'
            - 'LICENSE'

concurrency:
    group: deploy
    cancel-in-progress: true

jobs:
    analyze:
        uses: ./.github/workflows/analyze.yml
    docker:
        needs: analyze
        uses: ./.github/workflows/docker.yml
        with:
            push: true
        secrets:
            NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
            NEXT_PUBLIC_API_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_API_GRAPHQL_URL }}
            NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID }}
            DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
            WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
