name: Merge Dependabot

on:
    pull_request:
        branches: [ master ]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
